### ISSUE TITLE
more consistent padding/spacing on homepage

### ISSUE THREAD

**Issue by tyler-vs** [tyler-vs/genesis#13]
inconsistent padding due to hard-coded style attributes in the wp-bakery plugin.

- [ ] hard-coded values removed
- [ ] move related page styles to single source (likely in theme options)

**Comment by tyler-vs** [comment]
added 

```css

@media (max-width: 425px) {
    #swiper1 {
        padding-bottom: 0;
    }
}

```

to remove too much padding on mobile for "swiper" section.

**Comment by tyler-vs** [comment]
to make all header styles the same, include this mod for the "eternal journey" header which was found in the wp-bakery "custom CSS" area on the page. See #10 to later move these styles found in here to a better location (if need be?)

```css

.rf-banner-row__text--left h2 {
    margin-top: 0;
    text-transform: uppercase;
    letter-spacing: -.02em;
    font-size: 2.000em;
}

```
