### ISSUE TITLE
Fix second line tabs

### ISSUE THREAD

**Issue by tyler-vs** [tyler-vs/genesis#8]
<img width="865" alt="screen shot 2018-08-02 at 10 28 11" src="https://user-images.githubusercontent.com/9139991/43590348-c9db690a-963e-11e8-8eb6-f3bb607177e2.png">

**Comment by tyler-vs** [comment]
it seems the media query is:
- 1200px
- 992px - 1199px
- 768px - 991px - starts tablet


```css
/* .product-template-default.single.single-product {} */


/* 
 * 1. reduce the padding so all items can fit on single line
 */

@media (min-width: 768px) and (max-width: 1199px) {

    main.col-md-9,
    body {
        background: #ff0 !important;
    }

    .single-product .nav.nav-tabs {

    }   

    .tours-tabs {

    }

    .tours-tabs .nav-tabs {

    }

    .tours-tabs .nav-tabs li {

    }

    .tours-tabs .nav-tabs li a {
        padding: 0 25px;
    }

}



```

optimized


```css
@media (min-width: 768px) and (max-width: 1199px) {
    .tours-tabs .nav-tabs li a {
        padding: 0 25px;
    }
}


```
