### ISSUE TITLE
Fix padding issues between desktop, tablet & mobile

### ISSUE THREAD

**Issue by tyler-vs** [tyler-vs/genesis#9]
wonky padding on mobile devices

<img width="659" alt="screen shot 2018-08-02 at 10 29 14" src="https://user-images.githubusercontent.com/9139991/43590416-ef42ef60-963e-11e8-8939-b18f6a2acbba.png">

**Comment by tyler-vs** [comment]
```css
/* 
 * home page padding fix
 * 1. re-apply margin 
 * 2. fix spacing
 * 3. smaller padding for smaller screen
 * 4. manuall apply bootstrap xs grid
 * 5. resize button with smaller padding
 */
@media (max-width: 425px) {
    /* 1. */
    .home .form-block {
        margin-top: -100px;
        margin-bottom: 0;
    }

    /* 2. */
    .home .title--center {
        margin-bottom: 40px;
        margin-top: 70px;
    }    
    
    /* 3. */
    .home .form-block--horizontal .form-block__form {
        padding: 20px 10px 0 10px;
    }
    
    /* 4. */
    .home .form-block__form [class*="col-sm"] {
        float: left;
    }
    /* 4. */
    .home .form-block__form .col-sm-10 {
        width: 58.33333333%;
    }
    /* 4. */
    .home .form-block__form .col-sm-2 {
        width:41.66666667%;
        padding-left: 0;
    }
    /* 5. */
    .home .form-block__form .col-sm-2 .atbtn {
        padding: 0 15px;
    }
}

```

**Comment by tyler-vs** [comment]
seems that hard coded style attributes are found in the wp-bakery plugin, avoid this practice

for posterity

```html

<div style="margin-top: -170px;">[tour_search_form_horizontal style="style1" hide_text_field="off" css_class="margin-bottom" title=""]</div>
&nbsp;

```

**Comment by tyler-vs** [comment]
- update the media queries to match
- move hard coded styles into the CSS


```css

/* 
 * home page padding fix
 * 1. re-apply margin 
 * 2. fix spacing
 * 3. smaller padding for smaller screen
 * 4. manuall apply bootstrap xs grid
 * 5. resize button with smaller padding
 * 6. re-apply normal styles for tablet/desktop
 */
/* @media (max-width: 425px) { */
@media (max-width: 768px) {
    /* 1. */
    .home .form-block {
        margin-top: -100px;
        margin-bottom: 0;
    }

    /* 2. */
    .home .title--center {
        margin-bottom: 40px;
        margin-top: 70px;
    }    
    
    /* 3. */
    .home .form-block--horizontal .form-block__form {
        padding: 20px 10px 0 10px;
    }
    
    /* 4. */
    .home .form-block__form [class*="col-sm"] {
        float: left;
    }
    /* 4. */
    .home .form-block__form .col-sm-10 {
        width: 58.33333333%;
    }
    /* 4. */
    .home .form-block__form .col-sm-2 {
        width:41.66666667%;
        padding-left: 0;
    }
    /* 5. */
    .home .form-block__form .col-sm-2 .atbtn {
        padding: 0 15px;
    }
}


@media (min-width: 768px) {
    .home .form-block {
        margin-top: -170px;
    }
}

```
